# Generated by Django 5.0 on 2024-03-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('about_me', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('oter', 'Иной')], max_length=8)),
                ('interests', models.CharField(choices=[('artist', 'художник'), ('musician', 'музыкант'), ('poet', 'поэт'), ('writer', 'писатель'), ('dancer', 'танцор'), ('spectator', 'просто зритель')], max_length=15)),
                ('subscription', models.IntegerField()),
                ('link_other_social_networks', models.TextField()),
                ('subscribes', models.ManyToManyField(to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
